### ISSUE TITLE
Exercise Week 4: Project week 2 Review

### ISSUE THREAD

**Issue by TaiNguyen2407** [aikkuvo333/react-website-portfolio#1]
Hello, Joni told me you were absent due to sickness last lecture and therefore, do not have a PR. I figure I'll do code review as a whole in this issue. 

**Application overview and understanding**

You have a clear readme with instructions to run locally. 

Code is understandable, for example in `Button.js`, you have Button component that express a clear action and classnames. 

**Code Structure and Quality**

You have a good code structure, you have files with clear names and they are in folder with clear structure, like `components` or `pages`. 

**Commit Analysis**

I can see that you have codes and commits in the main branch. I'd recommend to follow commit convention [link here](https://www.conventionalcommits.org/en/v1.0.0/) for commits. 

To develop a feature or a component, I'd also recommend to create a separate branch, commit your changes with clear messages and push into feature branch. Then create a PR to merge feature branch into main. This way you can preserve main branch as a source code where if your feature branch somehow causes error, then you can always come back to main. 

**Communication and Documentation**

I have no complaints about documentation as you have a nice-to-read readme with clear instructions. Great job

**Suggestions for Improvement**

Overall I think the codebase is great, you are heading to the right directions. 

Some points of improvements I'd like to make: 

- Clear commit messages
- Create a branch for every new feature - push commits and changes and create PR after finish developing 
-  You can have a new component in NavBar which can be called e.g NavLink, which will replace this block of code `<li className='nav-item'>
                <Link to='/contact' className='nav-links' onClick={closeMobileMenu}>
                  Contact
                </Link>
              </li>` as I can see some repetition. 
- Maybe having smaller folders in `components` or `pages` for different components and pages - reason is that each component or page come in 2, js and css files - therefore, it can create a more structural look on your repo

**Comment by aikkuvo333** [comment]
Thanks for the comments, I will apply the suggestions in the future
