### ISSUE TITLE
 Exercise Week 4: Project Week 2 Reviews by valtat

### ISSUE THREAD

**Issue by valtat** [aikkuvo333/react-website-portfolio#2]
**Application Overview Understanding**
The applications purpose is clear and defined well in both the project structure and the readme. It is following the standard react project structure and the naming is on point.

**Code Structure and Quality**
The code is nicely structured, components are being used and the code is easy to read & understand.

**Commit Analysis**
There isn't much commits, but the ones that are there are simple and informative - added feature, edited file etc.

**Communication and Documentation**
The documentation is well made and gives insight both on what the project is about, and an easy step by step installation guide.

**Suggestions for Improvement**
Project is in early stages, maybe slightly behind the rest of the class in this course. Try to add more components and build a well functioning app - so far it looks like there is a navbar and a button component made, which is a good start.

**Comment by aikkuvo333** [comment]
Thanks for the comments, i will apply the suggestions in the future
