### ISSUE TITLE
As an user, I want to Contact the owner of the page through a contact form

### ISSUE THREAD

**Issue by aikkuvo333** [aikkuvo333/react-website-portfolio#3]
- Create a form for name, email and message and a submit button.
- Make sure that required fields are filled with proper syntax.
- Check if I've received a message.

**Comment by viettrung2103** [comment]
The user story is descriptive and the bullet points is easy to understand.
Code Structure and Quality:
- method name is descriptive and modular
Commit Analysis
- Short and concise commit
I notice that the components folder contains many files already, I think you should put these components into their own features.

**Comment by aikkuvo333** [comment]
Thanks for the feedback! I agree with the files sortment, i will need to sort them into smaller chunks
